exports.style = {
    container: {
        flex: 1,
    },
    topContainer: {
        flex: 2,
        alignItems: 'center',
        marginHorizontal: 10,
        zIndex: 1,
    },
    header: {
        fontSize: 22,
        fontWeight: '500',
        color: '#000',
        marginBottom: 20,
        opacity: 0.7,
    },
    signupOption: {
        paddingHorizontal: 25,
        marginVertical: 15,
        alignItems: 'center',
        flexDirection: 'row',
        backgroundColor: '#fff',
        height: 60,
        borderRadius: 10,
    },
    signupFB: {
        paddingHorizontal: 25,
        marginVertical: 15,
        alignItems: 'center',
        flexDirection: 'row',
        backgroundColor: '#1877F2',
        height: 60,
        borderRadius: 10,
    },
    signupEmail: {
        paddingHorizontal: 25,
        marginVertical: 15,
        alignItems: 'center',
        flexDirection: 'row',
        backgroundColor: '#000',
        height: 60,
        borderRadius: 10,
    },
    signupOptionText: {
        fontSize: 16,
        fontWeight: '500',
        marginLeft: 15,
    },
    signupTextLight: {
        fontSize: 16,
        fontWeight: '500',
        marginLeft: 15,
        color: '#fff',
    },
    logo: {
        resizeMode: 'contain',
        height: 50,
        width: 230,
        marginVertical: 15,
    },
    bottomContainer: {
        flex: 1,
        marginHorizontal: 10,
        zIndex: 0,
    },
    loginTextRow: {
        flex: 1,
        justifyContent: 'flex-end',
        alignItems: 'center',
        marginBottom: 10,
    },
    loginText: {
        fontSize: 16,
        color: '#000',
    },
    loginTextFlare: {
        fontSize: 16,
        color: '#FF7A01',
    },
    car: {
        position: 'absolute',
        right: -100,
        bottom: 100,
        opacity: 0.7,
        zIndex: 0,
    },
    optionLogo: {
        height: 34,
        width: 34,
    },
    shadowProp: {
        shadowColor: '#171717',
        shadowOffset: { width: -2, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
    },
}
